Feat: delete default labels in repo
amatkivskiy/github-labels-creator pull request #1
Opened 2018-10-03 08:47 UTC by lamrak

2018-10-04 09:55 UTC, amatkivskiy requested changes

2018-10-04 09:55 UTC, amatkivskiy commented on github_labels_creator.sh
> +echo "This script will delete default labels and create c repustom repository labels."
please fix typo in **repustom**.

2018-10-05 11:11 UTC, lamrak commented
What is wrong with `repusome`? I spent a lot of time inventing this word... )))

2018-10-09 08:22 UTC, amatkivskiy approved these changes
Nice job 👍 🥇 @lamrak

2018-10-09 08:22 UTC, merged